In [2]:
import numpy as np
arr=np.arange(0,50,5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [3]:
arr>15

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [5]:
arr[arr>15]

array([20, 25, 30, 35, 40, 45])

In [6]:
(arr>15) & (arr!=40)

array([False, False, False, False,  True,  True,  True,  True, False,
        True])

In [7]:
arr[(arr>15)&(arr!=40)]

array([20, 25, 30, 35, 45])

In [9]:
(arr<10) | (arr>=20)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [10]:
arr[(arr<10)|(arr>=20)]

array([ 0,  5, 20, 25, 30, 35, 40, 45])

In [12]:
np.logical_or(arr<10,arr>=20)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [13]:
np.where(arr<=43)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)

In [14]:
arr[(arr<10) | (arr>=20) & (arr!=40)]

array([ 0,  5, 20, 25, 30, 35, 45])

In [28]:
newarr=np.eye(4)
newarr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
mask=(newarr==0)^(newarr==2)
mask

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])