In [5]:
import numpy as np
arr=np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [6]:
arr[[3,0,1],:3]

array([[15, 16, 17],
       [ 0,  1,  2],
       [ 5,  6,  7]])

In [7]:
arr.sum()

190

In [8]:
arr[arr.sum(axis=1)>10,2:]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [9]:
arr[1, arr.sum(axis=0)>30]

array([6, 7, 8, 9])

In [10]:
a = np.array([97,101,105,111,117,125])
b = np.array(['a','e','i','o','u','y'])
c=(a>100) & (a<110)
b[c]

array(['e', 'i'], dtype='<U1')

In [11]:
nextarr=np.array([0,4,1,2,0,4])

In [12]:
nextarrshaped=nextarr.reshape(2,3)

In [13]:
nextarrshaped[0].max()

4

In [14]:
nextarrshaped[1].max()

4

In [15]:
last=np.arange(11)
last

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
lastf=(last>3) & (last<8)

In [17]:
last[lastf]

array([4, 5, 6, 7])

In [20]:
last[lastf]=-last[lastf]
last


array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])