In [1]:
import numpy as np
macierz_1=np.array([[1,3,6],[7,1,1],[7,2,7]])
print(f'Macierz 1\n{macierz_1}')
macierz_2=np.array([[-9,3,7],[7,3,1],[-1,-9,5]])
print(f'Macierz 2\n{macierz_2}')


Macierz 1
[[1 3 6]
 [7 1 1]
 [7 2 7]]
Macierz 2
[[-9  3  7]
 [ 7  3  1]
 [-1 -9  5]]


In [2]:
macierz_1+macierz_2

array([[-8,  6, 13],
       [14,  4,  2],
       [ 6, -7, 12]])

In [3]:
macierz_1*10

array([[10, 30, 60],
       [70, 10, 10],
       [70, 20, 70]])

In [4]:
macierz_1*macierz_2


array([[ -9,   9,  42],
       [ 49,   3,   1],
       [ -7, -18,  35]])

In [5]:
arr=np.arange(0,101,10)
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [7]:
left=np.arange(10).reshape(5,2)
right=np.arange(5).reshape(5,1)
left

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
right

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [9]:
np.sqrt(arr)

array([ 0.        ,  3.16227766,  4.47213595,  5.47722558,  6.32455532,
        7.07106781,  7.74596669,  8.36660027,  8.94427191,  9.48683298,
       10.        ])

In [10]:
arrm=np.array([[0,4,1],[2,0,4]])
arrm

array([[0, 4, 1],
       [2, 0, 4]])

In [11]:
arrm[0].max()

4

In [12]:
arrm[1].max()

4

In [13]:
arrm[0].min()

0

In [15]:
wektor=np.random.uniform(0,1,10)
wektor

array([0.62650321, 0.38319441, 0.04778587, 0.01025949, 0.50845459,
       0.55572265, 0.98515762, 0.74786429, 0.59297449, 0.82802863])

In [20]:
target=0.5
index=np.abs(wektor-target).argmin()
index
wektor[index]

0.508454586291494

In [25]:
vec20=np.random.rand(21)
vec20

array([0.88399078, 0.6654222 , 0.85558082, 0.89674924, 0.93606577,
       0.09663946, 0.22269755, 0.2704832 , 0.53214082, 0.60132758,
       0.13308776, 0.13931364, 0.46489355, 0.12194598, 0.06766674,
       0.50791314, 0.24539359, 0.94610756, 0.61728198, 0.6103169 ,
       0.25730933])

In [34]:
maks=np.argmax(vec20)
vec20[maks]=0
vec20

array([0.88399078, 0.6654222 , 0.85558082, 0.89674924, 0.        ,
       0.09663946, 0.22269755, 0.2704832 , 0.53214082, 0.60132758,
       0.13308776, 0.13931364, 0.46489355, 0.12194598, 0.06766674,
       0.50791314, 0.24539359, 0.        , 0.61728198, 0.6103169 ,
       0.25730933])

In [36]:
lista=np.array([5, 0.0249139 , 0.11873564, 0., 0.72321586, 11308494, 0.29931472, 0.24439968, 0.61251754, 4])
mask=lista%1==0
lista[mask]

array([5.0000000e+00, 0.0000000e+00, 1.1308494e+07, 4.0000000e+00])