In [2]:
import numpy as np
my_arr=np.arange(21)
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [4]:
import numpy as np
two_dim=np.array([[0,10,20],[5,15,25],[100,200,300]])
two_dim[1][0]

5

In [5]:
two_dim[2][0]

100

In [6]:
two_dim[1:3,:2]

array([[  5,  15],
       [100, 200]])

In [7]:
two_dim[0:1,:1]

array([[0]])

In [8]:
two_dim[1:1]

array([], shape=(0, 3), dtype=int32)

In [9]:
two_dim[2:,2:]

array([[300]])

In [10]:
my_rr=np.arange(25).reshape(5,5)

In [11]:
my_rr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
vals=np.array([100,5,0])
select=np.random.randint(0,3,size=(4,3))
vals

array([100,   5,   0])

In [13]:
vals

array([100,   5,   0])

In [14]:
select

array([[0, 2, 0],
       [1, 2, 2],
       [2, 2, 2],
       [2, 1, 1]])

In [15]:
vals[select]

array([[100,   0, 100],
       [  5,   0,   0],
       [  0,   0,   0],
       [  0,   5,   5]])

In [17]:
vals[[0,2,0]]

array([100,   0, 100])

In [18]:
#basic indexing
arr=np.arange(10)
slice_of_arr=arr[:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [19]:
slice_of_arr[:]=100
slice_of_arr

array([100, 100, 100, 100, 100])

In [20]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [22]:
#fancy indexing
fancy_arr=np.arange(10)
fancy_index_arr=fancy_arr[np.arange(5)]
fancy_index_arr

array([0, 1, 2, 3, 4])

In [27]:
fancy_index_arr[:]=100
fancy_index_arr

array([100, 100, 100, 100, 100])

In [26]:
fancy_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
macierz = np.arange(9).reshape(3, 3)
print(macierz)
macierz[-1, -1] = 999
macierz[1:, 1:] = 0
print('\n', macierz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[0 1 2]
 [3 0 0]
 [6 0 0]]
The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.


In [32]:
work=np.arange([1,2,0,0,4,0])

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [30]:
work[-1,-1]=100
work

NameError: name 'work' is not defined