In [1]:
import numpy as np
np.__version__

'1.26.4'

In [2]:
import numpy as np
exams=np.asarray([[100,200,50,400], [50,0,0,100], [350,100,50,200]])
exams

array([[100, 200,  50, 400],
       [ 50,   0,   0, 100],
       [350, 100,  50, 200]])

In [7]:
my_list=[i for i in range(1000000)]
%time for _ in range(10): my_list2=[x**2 for x in my_list]
print(my_list)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [8]:
my_array=np.arange(1000000)
%time for _ in range(10): my_array2=my_array**2
print(my_array)

CPU times: total: 31.2 ms
Wall time: 41.2 ms
[     0      1      2 ... 999997 999998 999999]


In [9]:
one_dim=np.array([1,2,3,4])
type(one_dim)

numpy.ndarray

In [10]:
one_dim.shape

(4,)

In [11]:
one_dim.ndim

1

In [13]:
one_dim_horizontal=np.array([[1,2,3,4]])
print(one_dim_horizontal.shape)
print(one_dim_horizontal.ndim)
one_dim_horizontal

(1, 4)
2


array([[1, 2, 3, 4]])

In [14]:
one_dim_vertical=one_dim_horizontal.reshape(-1,1)
one_dim_vertical

array([[1],
       [2],
       [3],
       [4]])

In [15]:
arr_01 = np.array([5, 10, 20])
print(arr_01, arr_01.dtype)
arr_02 = np.array([5, 10, 20.0])
print(arr_02, arr_02.dtype)
arr_03 = np.array([5, 10, '20'])
print(arr_03, arr_03.dtype)

[ 5 10 20] int32
[ 5. 10. 20.] float64
['5' '10' '20'] <U11


In [16]:
np.random.rand(10)

array([0.7125083 , 0.07314553, 0.67214596, 0.51873879, 0.1542455 ,
       0.39033263, 0.84679166, 0.30638746, 0.42535874, 0.93052194])

In [20]:
row=np.arange(5)
print(row)
matrix=np.tile(row, (5,1))
print(matrix)


[0 1 2 3 4]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
